In [51]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("archive.zip")

In [3]:
data.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [6]:
data.shape

(13320, 9)

In [7]:
data.columns

Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft', 'bath', 'balcony', 'price'],
      dtype='object')

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [13]:
for column in data.columns:
    print(data[column].value_counts())
    print("*"*20)

area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64
********************
availability
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
15-Aug               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: count, Length: 81, dtype: int64
********************
location
Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: count, Length: 1305, dtype: int64
********************
size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
14 BHK           1
13 BHK           1
12 Bedroom       1
27 BHK           1
43 Bedroom       1
16 BHK           1
19 BHK           1
18 Bedroom       1
Name: count, dtype: int64
********************
society
GrrvaGr    80
PrarePa    76
Sryalan    59
Prtates    59
GMown E    56
           ..
Amionce     1
JaghtDe     1
Jauraht     1
Brity U     1
RSntsAp     1
Name: count, Length: 2688, dtype: int64
********************
total_sqft
1200    843
1100    221
1500    205
2400    196
600     180
       ...
3580      1
2461      1
1437      1
2155      1
4689      1
Name: count, Length: 2117, dtype: int64
********************
bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
13.0       3
11.0       3
16.0       2
27.0       1
40.0       1
15.0       1
14.0       1
18.0       1
Name: count, dtype: int64
********************
balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64
********************
price
75.00     310
65.00     302
55.00     275
60.00     270
45.00     240
         ...
351.00      1
54.10       1
80.64       1
32.73       1
488.00      1
Name: count, Length: 1994, dtype: int64
********************

In [14]:
data.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [15]:
data.drop(columns=["area_type","availability","society","balcony"],inplace=True)

In [16]:
data.isnull().sum()

location       1
size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [17]:
data.describe()

               bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  object
 1   size        13304 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [19]:
data["location"].value_counts()

location
Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: count, Length: 1305, dtype: int64

In [20]:
data["location"]=data["location"].fillna("Sarjapur  Road")

In [21]:
data["size"].value_counts()

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
14 BHK           1
13 BHK           1
12 Bedroom       1
27 BHK           1
43 Bedroom       1
16 BHK           1
19 BHK           1
18 Bedroom       1
Name: count, dtype: int64

In [22]:
data["size"]=data["size"].fillna("2 BHK")

In [24]:
data["bath"].value_counts()

bath
1.0       5
3.0       2
788.0     1
6908.0    1
3286.0    1
1226.0    1
524.0     1
273.0     1
102.0     1
64.0      1
43.0      1
13.0      1
7.0       1
2.0       1
Name: count, dtype: int64

In [25]:
data["bath"]=data["bath"].fillna(data["bath"].median())

In [26]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13320 non-null  object
 1   size        13320 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13320 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [27]:
data["bhk"]=data["size"].str.split().str.get(0).astype(int)

In [28]:
data["bhk"]

0        2
1        4
2        3
3        3
4        2
        ..
13315    5
13316    4
13317    2
13318    4
13319    1
Name: bhk, Length: 13320, dtype: int64

In [29]:
data[data.bhk>20]

                       location        size total_sqft  bath  price  bhk
1718  2Electronic City Phase II      27 BHK       8000  13.0  230.0   27
4684                Munnekollal  43 Bedroom       2400  13.0  660.0   43

In [30]:
data["total_sqft"].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      shape=(2117,), dtype=object)

In [31]:
def convertRange(x):
    temp = x.split("-")
    if len(temp) == 2:
        return (float(temp[0])+float(temp[1]))/2
    try:
        return float(x)
    except:
        return None

In [32]:
data["total_sqft"]=data["total_sqft"].apply(convertRange)

In [33]:
data.head()

                   location       size  total_sqft    bath   price  bhk
0  Electronic City Phase II      2 BHK      1056.0    13.0   39.07    2
1          Chikka Tirupathi  4 Bedroom      2600.0   788.0  120.00    4
2               Uttarahalli      3 BHK      1440.0  6908.0   62.00    3
3        Lingadheeranahalli      3 BHK      1521.0  3286.0   95.00    3
4                  Kothanur      2 BHK      1200.0  1226.0   51.00    2

In [ ]:
#price per Sqft

In [34]:
data["price_per_sqft"]=data["price"]*100000/data["total_sqft"]

In [35]:
data["price_per_sqft"]

0         3699.810606
1         4615.384615
2         4305.555556
3         6245.890861
4         4250.000000
             ...
13315     6689.834926
13316    11111.111111
13317     5258.545136
13318    10407.336319
13319     3090.909091
Name: price_per_sqft, Length: 13320, dtype: float64

In [36]:
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694     13.975976    112.565627      2.802778    7.907501e+03
std     1238.405258     67.482972    148.971674      1.294496    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000     13.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000     13.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000     13.000000    120.000000      3.000000    7.311746e+03
max    52272.000000   6908.000000   3600.000000     43.000000    1.200000e+07

In [37]:
data["location"].value_counts()

location
Whitefield                        540
Sarjapur  Road                    400
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: count, Length: 1305, dtype: int64

In [38]:
data["location"]=data["location"].apply(lambda x: x.strip())
location_count=data["location"].value_counts()

In [39]:
location_count

location
Whitefield                        541
Sarjapur  Road                    400
Electronic City                   304
Kanakpura Road                    273
Thanisandra                       237
                                 ...
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: count, Length: 1294, dtype: int64

In [40]:
location_count_less_10 = location_count[location_count<=10]
location_count_less_10

location
Dairy Circle                      10
Nagappa Reddy Layout              10
Basapura                          10
1st Block Koramangala             10
Sector 1 HSR Layout               10
                                  ..
Bapuji Layout                      1
1st Stage Radha Krishna Layout     1
BEML Layout 5th stage              1
singapura paradise                 1
Abshot Layout                      1
Name: count, Length: 1053, dtype: int64

In [42]:
data["location"]=data["location"].apply(lambda x: "other" if x in location_count_less_10 else x)

In [43]:
data["location"].value_counts()

location
other                 2885
Whitefield             541
Sarjapur  Road         400
Electronic City        304
Kanakpura Road         273
                      ...
Nehru Nagar             11
Banjara Layout          11
LB Shastri Nagar        11
Pattandur Agrahara      11
Narayanapura            11
Name: count, Length: 242, dtype: int64

In [44]:
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694     13.975976    112.565627      2.802778    7.907501e+03
std     1238.405258     67.482972    148.971674      1.294496    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000     13.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000     13.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000     13.000000    120.000000      3.000000    7.311746e+03
max    52272.000000   6908.000000   3600.000000     43.000000    1.200000e+07

In [45]:
(data["total_sqft"]/data["bhk"]).describe()

count    13274.000000
mean       575.074878
std        388.205175
min          0.250000
25%        473.333333
50%        552.500000
75%        625.000000
max      26136.000000
dtype: float64

In [46]:
data=data[((data["total_sqft"]/data["bhk"])>=300)]
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  12530.000000  12530.000000  12530.000000  12530.000000    12530.000000
mean    1594.564544     14.035116    111.382401      2.650838     6303.979357
std     1261.271296     69.577039    152.077329      0.976678     4162.237981
min      300.000000      1.000000      8.440000      1.000000      267.829813
25%     1116.000000     13.000000     49.000000      2.000000     4210.526316
50%     1300.000000     13.000000     70.000000      3.000000     5294.117647
75%     1700.000000     13.000000    115.000000      3.000000     6916.666667
max    52272.000000   6908.000000   3600.000000     16.000000   176470.588235

In [48]:
data.shape

(12530, 7)

In [49]:
data.price_per_sqft.describe()

count     12530.000000
mean       6303.979357
std        4162.237981
min         267.829813
25%        4210.526316
50%        5294.117647
75%        6916.666667
max      176470.588235
Name: price_per_sqft, dtype: float64

In [ ]:
#Remove Outliers

In [52]:
def remove_outliers_sqft(df):
    df_output = pd.DataFrame()
    for key,subdf in df.groupby("location"):
        m= np.mean(subdf.price_per_sqft)
        st= np.std(subdf.price_per_sqft)
        gen_df=subdf[(subdf.price_per_sqft>(m-st)) & (subdf.price_per_sqft<=(m+st))]
        df_output =pd.concat([df_output,gen_df],ignore_index=True)
    return df_output
data = remove_outliers_sqft(data)
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  10301.000000  10301.000000  10301.000000  10301.000000    10301.000000
mean    1508.440608     14.252014     91.286372      2.574896     5659.062876
std      880.694214     76.730308     86.342786      0.897649     2265.774749
min      300.000000      1.000000     10.000000      1.000000     1250.000000
25%     1110.000000     13.000000     49.000000      2.000000     4244.897959
50%     1286.000000     13.000000     67.000000      2.000000     5175.600739
75%     1650.000000     13.000000    100.000000      3.000000     6428.571429
max    30400.000000   6908.000000   2200.000000     16.000000    24509.803922

In [57]:
def bhk_outlier_remover(df):
    exclude_indices = np.array([])

    for location, location_df in df.groupby("location"):
        bhk_stats = {}

        for bhk, bhk_df in location_df.groupby("bhk"):
            bhk_stats[bhk] = {
                "mean": np.mean(bhk_df.price_per_sqft),
                "std": np.std(bhk_df.price_per_sqft),
                "count": bhk_df.shape[0]
            }

        print(location, bhk_stats)

        for bhk, bhk_df in location_df.groupby("bhk"):
            stats = bhk_stats.get(bhk - 1)

            if stats and stats["count"] > 5:
                exclude_indices = np.append(
                    exclude_indices,
                    bhk_df[
                        bhk_df.price_per_sqft < stats["mean"]
                    ].index.values
                )

    return df.drop(exclude_indices, axis="index")

In [58]:
data=bhk_outlier_remover(data)

1st Block Jayanagar {2: {'mean': np.float64(11983.805668016194), 'std': 0.0, 'count': 1}, 3: {'mean': np.float64(11756.16905248807), 'std': 701.6243657657865, 'count': 3}, 4: {'mean': np.float64(15018.711280365416), 'std': 1.2278182423353805, 'count': 3}}
1st Phase JP Nagar {1: {'mean': np.float64(5952.380952380952), 'std': 0.0, 'count': 1}, 2: {'mean': np.float64(7931.806799837383), 'std': 1534.1422783514054, 'count': 8}, 3: {'mean': np.float64(9151.192151725822), 'std': 1054.731726021645, 'count': 7}, 4: {'mean': np.float64(7537.92218148637), 'std': 1607.0591069513537, 'count': 3}, 5: {'mean': np.float64(5666.666666666667), 'std': 0.0, 'count': 1}}
2nd Phase Judicial Layout {2: {'mean': np.float64(3851.8518518518517), 'std': 497.593660834978, 'count': 3}, 3: {'mean': np.float64(3620.93991671624), 'std': 241.87983343248052, 'count': 5}}
2nd Stage Nagarbhavi {4: {'mean': np.float64(15891.203703703704), 'std': 1668.9846920398563, 'count': 4}, 6: {'mean': np.float64(16891.666666666668), 'std': 1858.333333333333, 'count': 2}}
5th Block Hbr Layout {2: {'mean': np.float64(4755.410708222867), 'std': 374.06419031565235, 'count': 3}, 3: {'mean': np.float64(5511.811023622047), 'std': 0.0, 'count': 1}, 5: {'mean': np.float64(3611.1111111111113), 'std': 0.0, 'count': 1}, 6: {'mean': np.float64(5882.35294117647), 'std': 0.0, 'count': 1}}
5th Phase JP Nagar {1: {'mean': np.float64(4628.623188405797), 'std': 371.376811594203, 'count': 2}, 2: {'mean': np.float64(5067.359785883266), 'std': 453.24956183513086, 'count': 17}, 3: {'mean': np.float64(5112.892626961968), 'std': 526.8794907246175, 'count': 8}, 5: {'mean': np.float64(4325.0), 'std': 75.0, 'count': 2}}
6th Phase JP Nagar {2: {'mean': np.float64(5932.976565810137), 'std': 671.9347030151997, 'count': 8}, 3: {'mean': np.float64(8403.2863080867), 'std': 1515.4146231166221, 'count': 5}, 4: {'mean': np.float64(7704.160246533128), 'std': 0.0, 'count': 1}}
7th Phase JP Nagar {1: {'mean': np.float64(6133.333333333334), 'std': 133.33333333333348, 'count': 2}, 2: {'mean': np.float64(6272.516842644273), 'std': 1012.7881476778178, 'count': 40}, 3: {'mean': np.float64(6612.861682598103), 'std': 1181.6582893458344, 'count': 57}, 4: {'mean': np.float64(6028.22068063778), 'std': 1482.7661351832348, 'count': 2}}
8th Phase JP Nagar {1: {'mean': np.float64(6357.427937915743), 'std': 267.1694064501245, 'count': 4}, 2: {'mean': np.float64(4324.406715739656), 'std': 1131.8308808521078, 'count': 22}, 3: {'mean': np.float64(4293.744876160689), 'std': 723.4267508470377, 'count': 17}, 4: {'mean': np.float64(4539.6147062813725), 'std': 195.35428340140427, 'count': 3}, 5: {'mean': np.float64(4335.260115606937), 'std': 0.0, 'count': 1}}
9th Phase JP Nagar {1: {'mean': np.float64(3333.3333333333335), 'std': 0.0, 'count': 1}, 2: {'mean': np.float64(4653.05138390364), 'std': 834.4408302683472, 'count': 20}, 3: {'mean': np.float64(4518.339436369508), 'std': 790.2476753262926, 'count': 9}, 4: {'mean': np.float64(5336.8421052631575), 'std': 800.5999597024291, 'count': 3}}
AECS Layout {2: {'mean': np.float64(4921.300339526721), 'std': 619.6355499375203, 'count': 7}, 3: {'mean': np.float64(4500.0), 'std': 0.0, 'count': 1}}
Abbigere {1: {'mean': np.float64(3310.9205535075066), 'std': 610.6480739434737, 'count': 2}, 2: {'mean': np.float64(4058.165803016323), 'std': 62.23518728011486, 'count': 13}, 3: {'mean': np.float64(3571.4285714285716), 'std': 0.0, 'count': 1}, 6: {'mean': np.float64(3165.4545454545455), 'std': 74.5454545454545, 'count': 2}, 8: {'mean': np.float64(5000.0), 'std': 0.0, 'count': 1}}
Akshaya Nagar {2: {'mean': np.float64(4781.22783734999), 'std': 453.10974836521865, 'count': 17}, 3: {'mean': np.float64(5294.361032273932), 'std': 513.4396107693667, 'count': 30}}
Ambalipura {1: {'mean': np.float64(5690.909090909091), 'std': 0.0, 'count': 1}, 2: {'mean': np.float64(5886.737386783397), 'std': 736.0640513407117, 'count': 10}, 3: {'mean': np.float64(6331.134555298749), 'std': 569.718562351169, 'count': 7}, 4: {'mean': np.float64(5503.386809269163), 'std': 339.75044563279835, 'count': 2}}
Ambedkar Nagar {2: {'mean': np.float64(6454.091928430547), 'std': 182.0843219299883, 'count': 5}, 3: {'mean': np.float64(6572.746532916982), 'std': 422.13464472691317, 'count': 19}, 4: {'mean': np.float64(7684.086312870249), 'std': 531.2111375546801, 'count': 2}}
Amruthahalli {1: {'mean': np.float64(4020.618556701031), 'std': 0.0, 'count': 1}, 2: {'mean': np.float64(4953.838379629301), 'std': 823.6966143070669, 'count': 12}, 3: {'mean': np.float64(5574.846418310635), 'std': 1077.4444900329127, 'count': 7}}
Anandapura {2: {'mean': np.float64(4335.741837049203), 'std': 710.6695705040866, 'count': 14}, 3: {'mean': np.float64(4376.900862764794), 'std': 811.4741024839058, 'count': 5}, 4: {'mean': np.float64(5145.797598627787), 'std': 0.0, 'count': 1}}
Ananth Nagar {1: {'mean': np.float64(2800.0), 'std': 0.0, 'count': 4}, 2: {'mean': np.float64(3015.4242497371583), 'std': 491.5389870277813, 'count': 19}, 3: {'mean': np.float64(3239.9055148973916), 'std': 333.6052126335633, 'count': 3}}
Anekal {1: {'mean': np.float64(3307.549188983317), 'std': 602.8526665064047, 'count': 6}, 2: {'mean': np.float64(3418.531131818201), 'std': 543.1514964904059, 'count': 22}, 3: {'mean': np.float64(4075.680581158921), 'std': 340.19143395777115, 'count': 4}, 4: {'mean': np.float64(3000.0), 'std': 0.0, 'count': 1}}
Anjanapura {2: {'mean': np.float64(3451.5654968214635), 'std': 402.7964034804156, 'count': 7}, 3: {'mean': np.float64(4783.11324361657), 'std': 2019.9576386770505, 'count': 4}, 4: {'mean': np.float64(3852.102102102102), 'std': 796.5465465465463, 'count': 2}}
Ardendale {2: {'mean': np.float64(5596.405228758171), 'std': 122.54901960784309, 'count': 2}, 3: {'mean': np.float64(5378.1844320453965), 'std': 324.88136834734956, 'count': 10}, 4: {'mean': np.float64(6445.687085352693), 'std': 663.0498079730814, 'count': 7}}
Arekere {1: {'mean': np.float64(4666.666666666667), 'std': 0.0, 'count': 1}, 2: {'mean': np.float64(4884.730750645279), 'std': 371.1132245946985, 'count': 6}, 3: {'mean': np.float64(5822.747277384037), 'std': 695.6480303741811, 'count': 3}, 4: {'mean': np.float64(5239.852398523985), 'std': 0.0, 'count': 1}}
Attibele {1: {'mean': np.float64(2823.0512983538965), 'std': 440.885126183788, 'count': 18}, 2: {'mean': np.float64(3204.1609520225234), 'std': 617.2070386969107, 'count': 12}, 3: {'mean': np.float64(4330.95861895704), 'std': 1307.8696742735906, 'count': 4}, 4: {'mean': np.float64(3840.959409594096), 'std': 540.9594095940961, 'count': 2}}
BEML Layout {2: {'mean': np.float64(5944.048212904286), 'std': 1628.8084083258766, 'count': 6}, 3: {'mean': np.float64(4250.0), 'std': 0.0, 'count': 4}, 5: {'mean': np.float64(9375.0), 'std': 0.0, 'count': 1}}
BTM 2nd Stage {2: {'mean': np.float64(5621.791028153005), 'std': 795.7682556051348, 'count': 14}, 3: {'mean': np.float64(10282.08598547458), 'std': 3831.770494859885, 'count': 9}, 5: {'mean': np.float64(13913.04347826087), 'std': 0.0, 'count': 1}}
BTM Layout {1: {'mean': np.float64(4444.444444444444), 'std': 0.0, 'count': 1}, 2: {'mean': np.float64(5073.776447337828), 'std': 424.90705275056126, 'count': 4}, 3: {'mean': np.float64(5685.2029893641175), 'std': 881.6401846985812, 'count': 7}, 6: {'mean': np.float64(5000.0), 'std': 0.0, 'count': 1}}
Babusapalaya {2: {'mean': np.float64(3799.9594889549185), 'std': 423.8304869618115, 'count': 11}, 3: {'mean': np.float64(3669.941030877054), 'std': 601.932707346431, 'count': 10}}
Badavala Nagar {2: {'mean': np.float64(6357.9277864992155), 'std': 0.0, 'count': 2}, 3: {'mean': np.float64(6279.828480978357), 'std': 42.27887875035828, 'count': 7}}
Balagere {1: {'mean': np.float64(5865.01000449379), 'std': 539.315075028032, 'count': 9}, 2: {'mean': np.float64(6191.495143186286), 'std': 543.3822583816924, 'count': 28}}
Banashankari {1: {'mean': np.float64(8333.333333333334), 'std': 0.0, 'count': 2}, 2: {'mean': np.float64(5038.253269278571), 'std': 1168.5163463486565, 'count': 31}, 3: {'mean': np.float64(5817.282245183152), 'std': 1663.833391137828, 'count': 29}, 4: {'mean': np.float64(3800.0), 'std': 0.0, 'count': 1}}
Banashankari Stage II {2: {'mean': np.float64(8701.636799298034), 'std': 1030.287972433991, 'count': 4}, 3: {'mean': np.float64(10723.280423280425), 'std': 4231.90962768462, 'count': 6}, 4: {'mean': np.float64(12500.0), 'std': 0.0, 'count': 1}, 5: {'mean': np.float64(18214.285714285714), 'std': 3035.7142857142853, 'count': 2}}
Banashankari Stage III {2: {'mean': np.float64(5430.250387687147), 'std': 1871.4365421808766, 'count': 4}, 3: {'mean': np.float64(5330.43635317069), 'std': 1014.1370099612311, 'count': 10}, 4: {'mean': np.float64(7333.333333333333), 'std': 2054.8046676563254, 'count': 3}, 6: {'mean': np.float64(5000.0), 'std': 0.0, 'count': 1}}
Banashankari Stage V {2: {'mean': np.float64(3983.4541062801936), 'std': 527.4154589371976, 'count': 2}, 3: {'mean': np.float64(3581.57134026118), 'std': 544.8260330690271, 'count': 9}}
Banashankari Stage VI {2: {'mean': np.float64(5072.0195454829345), 'std': 22.81429179660186, 'count': 3}, 3: {'mean': np.float64(5006.925310122253), 'std': 23.924063833179062, 'count': 3}, 4: {'mean': np.float64(5041.801948051948), 'std': 2237.063491984229, 'count': 4}}
Banaswadi {1: {'mean': np.float64(6641.366223908918), 'std': 0.0, 'count': 1}, 2: {'mean': np.float64(5110.715347907356), 'std': 582.5694084547944, 'count': 10}, 3: {'mean': np.float64(4656.25), 'std': 0.0, 'count': 1}, 5: {'mean': np.float64(7356.8050446663165), 'std': 0.0, 'count': 1}}
Banjara Layout {2: {'mean': np.float64(6635.496110794916), 'std': 905.9365352849989, 'count': 3}, 3: {'mean': np.float64(5600.0), 'std': 0.0, 'count': 1}}
Bannerghatta {2: {'mean': np.float64(6630.037324398989), 'std': 872.6962508901346, 'count': 4}, 3: {'mean': np.float64(7565.595658950089), 'std': 786.4254337865935, 'count': 4}, 4: {'mean': np.float64(8398.03739052883), 'std': 97.90458840399697, 'count': 2}}
Bannerghatta Road {1: {'mean': np.float64(4932.455648926237), 'std': 741.987966876004, 'count': 5}, 2: {'mean': np.float64(5156.722324231199), 'std': 951.8519337869209, 'count': 59}, 3: {'mean': np.float64(5384.498056381959), 'std': 1219.6689012468119, 'count': 71}, 4: {'mean': np.float64(5968.786895986739), 'std': 1737.4673135012401, 'count': 8}, 5: {'mean': np.float64(5851.851851851852), 'std': 0.0, 'count': 1}, 6: {'mean': np.float64(8108.108108108108), 'std': 0.0, 'count': 1}}
Basavangudi {2: {'mean': np.float64(9700.42512839123), 'std': 665.8646001174526, 'count': 6}, 3: {'mean': np.float64(9210.853069429275), 'std': 904.4272935920624, 'count': 10}, 4: {'mean': np.float64(10095.80105992662), 'std': 95.80105992662084, 'count': 2}}
Basaveshwara Nagar {2: {'mean': np.float64(6750.0), 'std': 552.7707983925667, 'count': 5}, 3: {'mean': np.float64(7834.767884859602), 'std': 59.968957245661386, 'count': 2}, 5: {'mean': np.float64(11069.444444444445), 'std': 1847.2222222222217, 'count': 2}}
Battarahalli {2: {'mean': np.float64(4345.7243068848575), 'std': 823.6340914029164, 'count': 9}, 3: {'mean': np.float64(5015.40017552159), 'std': 337.7428143761158, 'count': 8}}
Begur {2: {'mean': np.float64(4961.668185533498), 'std': 39.10751993914706, 'count': 3}, 3: {'mean': np.float64(4510.654979278204), 'std': 599.1143016556773, 'count': 9}, 4: {'mean': np.float64(3906.25), 'std': 0.0, 'count': 1}}
Begur Road {2: {'mean': np.float64(3624.166282880882), 'std': 262.3730178311292, 'count': 35}, 3: {'mean': np.float64(3684.8720181009558), 'std': 378.82522322146735, 'count': 28}, 4: {'mean': np.float64(4787.9894501927365), 'std': 0.0, 'count': 1}}
Bellandur {1: {'mean': np.float64(4210.526315789473), 'std': 0.0, 'count': 1}, 2: {'mean': np.float64(5116.644099551324), 'std': 1016.3979870126873, 'count': 52}, 3: {'mean': np.float64(5647.571810653258), 'std': 1127.9673046785176, 'count': 31}, 4: {'mean': np.float64(6759.122130530177), 'std': 845.9579630611066, 'count': 4}}
Benson Town {2: {'mean': np.float64(12686.709975197631), 'std': 3611.8164390019756, 'count': 4}, 3: {'mean': np.float64(14313.731148045554), 'std': 2420.56421489562, 'count': 3}, 4: {'mean': np.float64(14856.497304850036), 'std': 282.5062734599014, 'count': 2}}
Bharathi Nagar {2: {'mean': np.float64(4813.740209190311), 'std': 471.43026983759114, 'count': 8}, 3: {'mean': np.float64(4200.120192307692), 'std': 0.0, 'count': 1}}
Bhoganhalli {2: {'mean': np.float64(5417.416718889453), 'std': 285.36806332317167, 'count': 12}, 3: {'mean': np.float64(6125.4200445093), 'std': 899.1112373435706, 'count': 13}, 4: {'mean': np.float64(5777.756745789307), 'std': 871.3161320532748, 'count': 11}}
Billekahalli {2: {'mean': np.float64(5962.1264143650205), 'std': 952.8379048046246, 'count': 7}, 3: {'mean': np.float64(6179.829109009818), 'std': 1029.8742088847782, 'count': 6}}
Binny Pete {1: {'mean': np.float64(8034.164957849169), 'std': 901.878395083154, 'count': 4}, 2: {'mean': np.float64(7933.924709828325), 'std': 1003.8042279006136, 'count': 2}, 3: {'mean': np.float64(8471.722137179819), 'std': 951.1093605219069, 'count': 6}, 4: {'mean': np.float64(8382.135462880804), 'std': 1141.674060928719, 'count': 2}}
Bisuvanahalli {2: {'mean': np.float64(3863.8012733035357), 'std': 405.2872025065846, 'count': 12}, 3: {'mean': np.float64(4006.5825354643744), 'std': 468.023038908377, 'count': 31}}
Bommanahalli {1: {'mean': np.float64(4302.184466019417), 'std': 552.1844660194174, 'count': 2}, 2: {'mean': np.float64(4544.41960101665), 'std': 569.7400942075514, 'count': 9}, 3: {'mean': np.float64(4254.328104328105), 'std': 505.922183603648, 'count': 4}, 4: {'mean': np.float64(4047.6190476190477), 'std': 0.0, 'count': 1}, 8: {'mean': np.float64(4666.666666666667), 'std': 0.0, 'count': 1}}
Bommasandra {2: {'mean': np.float64(3813.947572153106), 'std': 244.23665886444502, 'count': 19}, 3: {'mean': np.float64(3815.8530659565145), 'std': 403.8116627539011, 'count': 11}}
Bommasandra Industrial Area {2: {'mean': np.float64(2887.892987573868), 'std': 0.47920744469383775, 'count': 11}, 3: {'mean': np.float64(2863.160206574431), 'std': 59.9654742104211, 'count': 7}}
Bommenahalli {3: {'mean': np.float64(8565.382032363164), 'std': 1314.9620051314946, 'count': 3}, 4: {'mean': np.float64(8564.836466843257), 'std': 717.6221010374835, 'count': 6}}
Brookefield {2: {'mean': np.float64(5837.492693390221), 'std': 903.6255944977522, 'count': 19}, 3: {'mean': np.float64(5795.407173862258), 'std': 1201.0625471599164, 'count': 13}, 4: {'mean': np.float64(6680.252598242926), 'std': 2089.3417875296827, 'count': 7}, 5: {'mean': np.float64(8974.358974358975), 'std': 0.0, 'count': 1}}
Budigere {1: {'mean': np.float64(5155.722891566265), 'std': 166.41859289793305, 'count': 4}, 2: {'mean': np.float64(5034.160717791254), 'std': 199.14597741069483, 'count': 23}, 3: {'mean': np.float64(4995.782145950289), 'std': 304.7321376982579, 'count': 22}}
CV Raman Nagar {1: {'mean': np.float64(7092.198581560284), 'std': 0.0, 'count': 1}, 2: {'mean': np.float64(5155.724160108177), 'std': 750.6157631590067, 'count': 18}, 3: {'mean': np.float64(5069.1182815641005), 'std': 895.7302193450796, 'count': 8}}
Chamrajpet {1: {'mean': np.float64(16831.68316831683), 'std': 0.0, 'count': 1}, 2: {'mean': np.float64(9792.423102012144), 'std': 3818.3998448404645, 'count': 5}, 3: {'mean': np.float64(7141.805995187703), 'std': 751.0857983228121, 'count': 3}, 4: {'mean': np.float64(10827.574839290468), 'std': 1880.2064182378372, 'count': 2}}
Chandapura {1: {'mean': np.float64(2520.6090114704184), 'std': 140.15700556082749, 'count': 19}, 2: {'mean': np.float64(2822.6938747446193), 'std': 410.55761448180084, 'count': 37}, 3: {'mean': np.float64(2853.1236984866746), 'std': 427.6538083676819, 'count': 26}, 4: {'mean': np.float64(3498.942358540455), 'std': 0.0, 'count': 1}}
Channasandra {2: {'mean': np.float64(3613.5088756107493), 'std': 502.5086800433043, 'count': 24}, 3: {'mean': np.float64(4500.644242719408), 'std': 1005.213241509808, 'count': 9}, 4: {'mean': np.float64(5963.333333333333), 'std': 0.0, 'count': 1}, 6: {'mean': np.float64(4285.714285714285), 'std': 0.0, 'count': 1}}
Chikka Tirupathi {3: {'mean': np.float64(4090.4654941407116), 'std': 246.87536752515462, 'count': 4}, 4: {'mean': np.float64(4568.837506464278), 'std': 449.90860011916783, 'count': 7}}
Chikkabanavar {2: {'mean': np.float64(3979.526682999282), 'std': 296.21104114438486, 'count': 3}, 3: {'mean': np.float64(4242.424242424242), 'std': 757.5757575757575, 'count': 2}, 4: {'mean': np.float64(3252.032520325203), 'std': 0.0, 'count': 1}, 5: {'mean': np.float64(3645.833333333333), 'std': 395.83333333333326, 'count': 2}, 8: {'mean': np.float64(2750.0), 'std': 0.0, 'count': 1}}
Chikkalasandra {2: {'mean': np.float64(4680.665935758178), 'std': 906.7207027292567, 'count': 14}, 3: {'mean': np.float64(4209.541795721919), 'std': 468.54274526277595, 'count': 14}}
Choodasandra {2: {'mean': np.float64(4782.163531612381), 'std': 528.754856051744, 'count': 12}, 3: {'mean': np.float64(4993.1936034011), 'std': 599.6867241072546, 'count': 10}, 4: {'mean': np.float64(8645.533141210375), 'std': 0.0, 'count': 1}}
Cooke Town {2: {'mean': np.float64(9450.335685771604), 'std': 1592.310446826406, 'count': 3}, 3: {'mean': np.float64(11852.598087462115), 'std': 1661.385526814624, 'count': 4}, 4: {'mean': np.float64(11016.71535215839), 'std': 375.6897111327489, 'count': 2}}
Cox Town {2: {'mean': np.float64(8230.365020192607), 'std': 2084.870283562963, 'count': 5}, 3: {'mean': np.float64(7780.757079649942), 'std': 1186.6163940265649, 'count': 4}}
Cunningham Road {3: {'mean': np.float64(19562.042390433755), 'std': 1371.647354515775, 'count': 8}, 4: {'mean': np.float64(22399.47110781565), 'std': 2068.0898222124456, 'count': 3}}
Dasanapura {1: {'mean': np.float64(5790.960451977401), 'std': 0.0, 'count': 1}, 2: {'mean': np.float64(5113.831187981814), 'std': 479.0067310357899, 'count': 7}, 3: {'mean': np.float64(5032.659409020218), 'std': 255.05443234836684, 'count': 2}}
Dasarahalli {2: {'mean': np.float64(5117.938928017428), 'std': 689.5131286166418, 'count': 6}, 3: {'mean': np.float64(5324.248120300752), 'std': 390.03759398496277, 'count': 2}}
Devanahalli {1: {'mean': np.float64(4606.9148770709035), 'std': 456.2054151733658, 'count': 7}, 2: {'mean': np.float64(4936.153738448984), 'std': 478.78750862962505, 'count': 14}, 3: {'mean': np.float64(4865.343550039019), 'std': 459.80251272063725, 'count': 12}, 4: {'mean': np.float64(5981.308411214954), 'std': 0.0, 'count': 1}, 5: {'mean': np.float64(4166.666666666667), 'std': 0.0, 'count': 1}}
Devarachikkanahalli {1: {'mean': np.float64(3902.439024390244), 'std': 0.0, 'count': 1}, 2: {'mean': np.float64(4326.739586439991), 'std': 1082.6324000628515, 'count': 9}, 3: {'mean': np.float64(4404.02899440667), 'std': 596.4161034790261, 'count': 5}}
Dodda Nekkundi {2: {'mean': np.float64(4271.409551033765), 'std': 572.5384233681566, 'count': 19}, 3: {'mean': np.float64(5934.221068512782), 'std': 1020.763160342317, 'count': 7}}
Doddaballapur {1: {'mean': np.float64(7492.354740061162), 'std': 0.0, 'count': 1}, 3: {'mean': np.float64(6861.368629625442), 'std': 792.385913681854, 'count': 3}, 4: {'mean': np.float64(7306.716419287801), 'std': 1508.6011290881638, 'count': 4}}
Doddakallasandra {2: {'mean': np.float64(4009.260011822078), 'std': 22.428701187061954, 'count': 6}, 3: {'mean': np.float64(3999.4695049973843), 'std': 0.3068175498332698, 'count': 4}}
Doddathoguru {1: {'mean': np.float64(3193.939393939394), 'std': 145.7068518808643, 'count': 3}, 2: {'mean': np.float64(3695.715772231203), 'std': 513.1647769886983, 'count': 14}, 3: {'mean': np.float64(3920.463690699665), 'std': 643.1324346449559, 'count': 7}}
Domlur {1: {'mean': np.float64(9445.779914529914), 'std': 948.6331997307019, 'count': 3}, 2: {'mean': np.float64(7329.742881854468), 'std': 773.8913545349003, 'count': 3}, 3: {'mean': np.float64(8601.445470741792), 'std': 2229.6988314054834, 'count': 14}}

In [59]:
data.shape

(7360, 7)

In [60]:
data

,location,size,total_sqft,bath,price,bhk,price_per_sqft
0,1st Block Jayanagar,4 BHK,2850.0,13.0,428.0,4,15017.543860
1,1st Block Jayanagar,3 BHK,1630.0,13.0,194.0,3,11901.840491
2,1st Block Jayanagar,3 BHK,1875.0,13.0,235.0,3,12533.333333
3,1st Block Jayanagar,3 BHK,1200.0,13.0,130.0,3,10833.333333
4,1st Block Jayanagar,2 BHK,1235.0,13.0,148.0,2,11983.805668
...,...,...,...,...,...,...,...
10292,other,2 BHK,1200.0,13.0,70.0,2,5833.333333
10293,other,1 BHK,1800.0,13.0,200.0,1,11111.111111
10296,other,2 BHK,1353.0,13.0,110.0,2,8130.081301
10297,other,1 Bedroom,812.0,13.0,26.0,1,3201.970443
10300,other,4 BHK,3600.0,13.0,400.0,4,11111.111111

In [61]:
data.drop(columns=["size","price_per_sqft"],inplace=True)

In [ ]:
#cleaned Data

In [62]:
data.head()

              location  total_sqft  bath  price  bhk
0  1st Block Jayanagar      2850.0  13.0  428.0    4
1  1st Block Jayanagar      1630.0  13.0  194.0    3
2  1st Block Jayanagar      1875.0  13.0  235.0    3
3  1st Block Jayanagar      1200.0  13.0  130.0    3
4  1st Block Jayanagar      1235.0  13.0  148.0    2

In [63]:
data.to_csv("Cleaned_data.csv")

In [97]:
x=data.drop(columns=["price"])
y=data["price"]

In [67]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [108]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [91]:
print(x_train.shape)
print(x_test.shape)

(5888, 4)
(1472, 4)

In [ ]:
#Applying Linear Regression

In [101]:
columns_trans=make_column_transformer((OneHotEncoder(sparse_output=False),["location"]),remainder="passthrough")

In [102]:
scaler=StandardScaler()

In [103]:
lr= LinearRegression()

In [104]:
pipe=make_pipeline(columns_trans,scaler,lr)

In [105]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [106]:
y_pred_lr=pipe.predict(x_test)

In [128]:
r2_score(y_test,y_pred_lr)

0.8281460459895129

In [ ]:
#Applying Lasso

In [111]:
lasso =Lasso()

In [114]:
pipe=make_pipeline(columns_trans,scaler,lasso)

In [115]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('lasso', Lasso())])

In [116]:
y_pred_lasso=pipe.predict(x_test)
r2_score(y_test,y_pred_lasso)

0.8193065944047357

In [ ]:
#Applying Ridge

In [117]:
ridge=Ridge()

In [122]:
pipe=make_pipeline(columns_trans,scaler,ridge)

In [123]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('ridge', Ridge())])

In [125]:
y_pred_ridge=pipe.predict(x_test)
r2_score(y_test,y_pred_ridge)

0.8281621505892125

In [130]:
print("No Regularization:",r2_score(y_test,y_pred_lr))
print("Lasso:",r2_score(y_test,y_pred_lasso))
print("Ridge:",r2_score(y_test,y_pred_ridge))

No Regularization: 0.8281460459895129
Lasso: 0.8193065944047357
Ridge: 0.8281621505892125

In [131]:
import pickle

In [132]:
pickle.dump(pipe,open("RidgeModel.pkl","wb"))